apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: three-tier
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: frontend


# You have: 6 frontend pods
# PDB says: minAvailable = 2
# So: allowed disruptions = 6 - 2 = 4
# Kubernetes can evict: Up to 4 pods at a time
# Availability is guaranteed even during major node drains.
