apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: three-tier
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend


# You have: 6 frontend pods
# PDB says: maxUnavailable = 1
# So: Kubernetes will ensure at most 1 pod is unavailable at a time.
# This ensures 5 pods are always Running during a node drain.
# This shows stricter control than minAvailable.
