apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: three-tier
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend


# You have: 2 frontend pods
# PDB says: minAvailable = 1
# So: allowed disruptions = 2 - 1 = 1
# Kubernetes can evict: 1 pod at a time (not both!)
